version: '3'

services:
  reverse:
    image: nginx:alpine
    container_name: kiki_kibana_reverse
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kiki_elastic

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: kiki_elastic
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - kiki_elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kiki_kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
      - kiki_elastic

networks:
  kiki_elastic:
    driver: bridge